name: Android Internal Preview Build

on:
  push:
    branches:
      - main

jobs:
  android_preview:
    name: Build Android Internal APK
    type: build
    params:
      platform: android
      profile: preview
