ALTER TABLE "Profile"
ADD COLUMN IF NOT EXISTS "fitPreference" TEXT;

ALTER TABLE "SizeChartEntry"
ADD COLUMN IF NOT EXISTS "shoulderMinCm" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "shoulderMaxCm" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "footLengthMinCm" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "footLengthMaxCm" DOUBLE PRECISION;

ALTER TABLE "FitAssessment"
ADD COLUMN IF NOT EXISTS "variantId" TEXT,
ADD COLUMN IF NOT EXISTS "chosenSizeLabel" TEXT,
ADD COLUMN IF NOT EXISTS "recommendedSize" TEXT,
ADD COLUMN IF NOT EXISTS "fitLabel" TEXT,
ADD COLUMN IF NOT EXISTS "issues" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "explanation" TEXT,
ADD COLUMN IF NOT EXISTS "metadata" JSONB;
